# Hauptbuch Configuration File
# This file contains the main configuration for the Hauptbuch blockchain system

[system]
# System-wide configuration
name = "Hauptbuch"
version = "0.1.0"
environment = "development"  # development, staging, production
log_level = "info"  # trace, debug, info, warn, error

[consensus]
# Proof of Stake consensus configuration
validator_count = 100
stake_threshold = 1000000  # Minimum stake required to become a validator
slashing_percentage = 0.05  # 5% slashing for malicious behavior
block_time = 12  # seconds
epoch_length = 100  # blocks per epoch

[security]
# Security configuration
quantum_resistant = true
hybrid_crypto = true
nist_pqc_enabled = true
formal_verification = true

[crypto]
# Cryptographic configuration
nist_pqc = { enabled = true, ml_kem = true, ml_dsa = true, slh_dsa = true }
classical_crypto = { enabled = true, ecdsa = true, x25519 = true, aes_gcm = true }
zk_proofs = { halo2 = true, plonky3 = true, binius = false }  # Binius not yet available

[network]
# Network configuration
p2p_port = 30303
rpc_port = 8545
ws_port = 8546
max_peers = 50
discovery_enabled = true
nat_traversal = true

[performance]
# Performance optimization settings
parallel_execution = true
block_stm = true
optimistic_validation = true
quic_networking = true
sealevel_parallel = true
state_cache = true
max_workers = 8

[data_availability]
# Data availability layer configuration
provider = "celestia"  # celestia, avail, eigenda, dynamic
celestia = { enabled = true, rpc_url = "https://rpc.celestia.org" }
avail = { enabled = false, rpc_url = "https://rpc.avail.tools" }
eigenda = { enabled = false, rpc_url = "https://rpc.eigenda.org" }

[l2]
# Layer 2 configuration
rollups = { enabled = true, optimistic = true, zk = true }
zkevm = { enabled = true, sp1 = true, jolt = false }  # Jolt not yet available
eip4844 = { enabled = true, kzg_ceremony = true }

[based_rollup]
# Based rollup configuration
espresso_sequencer = { enabled = true, rpc_url = "https://rpc.espresso.org" }
hotstuff_bft = { enabled = true, committee_size = 21 }
preconfirmations = { enabled = true, timeout = 5000 }  # milliseconds

[cross_chain]
# Cross-chain interoperability
bridge = { enabled = true, multi_sig = true }
ibc = { enabled = true, client_verification = true }
ccip = { enabled = true, oracle_network = true }

[governance]
# Governance configuration
proposal_threshold = 0.01  # 1% of total supply
voting_period = 7  # days
execution_delay = 1  # days
quorum_threshold = 0.2  # 20% of total supply

[mev_protection]
# MEV protection configuration
encrypted_mempool = true
builder_separation = true
anti_frontrunning = true
mev_detection = true

[sharding]
# Sharding configuration
enabled = true
shard_count = 4
cross_shard_communication = true
state_synchronization = true

[tee]
# Trusted Execution Environment
intel_sgx = { enabled = true, attestation = true }
arm_trustzone = { enabled = false }
amd_sev = { enabled = false }

[zkml]
# Zero-Knowledge Machine Learning
enabled = true
ezkl = { enabled = false }  # Not yet available
halo2 = { enabled = true }
circuit_optimization = true

[zktls]
# Zero-Knowledge TLS
enabled = true
certificate_validation = true
handshake_proofs = true

[compliance]
# Regulatory compliance
enabled = true
jurisdictions = ["US", "EU", "UK", "JP"]
reporting_interval = 24  # hours
enforcement = true

[oracle]
# Oracle systems
predictive = { enabled = true, ml_models = true }
time_series = { enabled = true, forecasting = true }
risk_assessment = { enabled = true }

[restaking]
# EigenLayer restaking
eigenlayer = { enabled = true, liquid_restaking = true }
security_guarantees = true
decentralization_preservation = true

[monitoring]
# System monitoring
metrics_enabled = true
alerting = true
health_checks = true
performance_monitoring = true

[storage]
# Storage configuration
database = "rocksdb"
cache = "redis"
backup_interval = 24  # hours
compression = true

[api]
# API configuration
rpc_enabled = true
rest_api = true
graphql = true
rate_limiting = true
cors_enabled = true

[testing]
# Testing configuration
unit_tests = true
integration_tests = true
benchmarks = true
fuzzing = true
chaos_engineering = true

[development]
# Development settings
hot_reload = true
debug_mode = true
profiling = true
tracing = true
